apiVersion: v1
kind: Service
metadata:
  name: api-version
  labels:
    app: api-version
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http

  selector:
    app: api-version
    version: v1.0.0
